### PR TITLE
Bring tar runfiles up to feature parity with pkg_files.runfiles.

### PR DESCRIPTION
**Pull request by aiuto**
Bring tar runfiles up to feature parity with pkg_files.runfiles.
    
The bulk of the change is to have pkg_tar use `pkg_files%add_label_list` to process `srcs`.  That brings it in conformance with pkg_files and pkg_zip. This changes the behavior of runfiles to be useful, but it is a breaking change.
 
Fixes: #153
Fixes: #579
    
Other bits:
- do not fail verify_archive_test without a min_size or max_size
- change `data` file in the sample executable from BUILD to foo.cc so that it is easier to disambiguate from other files.
- fix bug in runfiles support where files were not added to file_deps list.
- fix bug in runfiles support where the runfiles base path was not computed correctly.
- buildifier to make the linters happy.

RELNOTES: Improved runfiles support in pkg_tar. Breaking change: we now require a Bazel that supports lambdas.

### CODE REVIEW

**Comment by alexeagle** [comment]
@aiuto what's needed to make this draft Ready for review? We're eager to get this in to fix python images.

**Comment by aiuto** [comment]
The refactoring PR #756 has to go in first. Then I need to rebase on that and add a legacy option.
It would also help if #749 were in too, then I can import to Google and test the legacy option.
About a day's work, when I get back from vacation.

**Comment by dieortin** [comment]
@aiuto both PRs are merged, is there anything we could do to help with this?

**Comment by aiuto** [comment]
I'm waiting on  https://github.com/bazelbuild/rules_pkg/pull/784 so CI can
be green again.

**Comment by ConnorJLatham** [comment]
will this change be pulled into an official release sometime soon? looks like the latest was from may

**Comment by aiuto** [comment]
Now that we are past the bazel 7 release and the holidays it might be time
for a new one.
It needs a little CI work first to make sure we are testing with bazel 6
(wihout bzlmod)
and 7 with both bzlmod and without.
Just a matter of an afternoon of grunt work.

**Pull request merged**
