### PR TITLE
Fixes #14: Ability to filter out packages in a repository by components

### LINKED ISSUE #14: Ability to filter out packages in a repository by component(s)
Component (or area) is described in the Debian documentation: https://wiki.debian.org/DebianRepository/Format#Components

This would be mostly useful for private repositories, where you might get separate components available in the same repository.

### PR DESCRIPTION
**Pull request by adragomir**

### CODE REVIEW

**Comment by adragomir** [comment]
@MarkusTeufelberger @philwo PTAL !
This adds a new feature, the ability to filter out packages in a repository by component.

**Comment by philwo** [comment]
@MarkusTeufelberger if you approve, I'll merge :)

**Comment by adragomir** [comment]
@MarkusTeufelberger any thoughts ? Thanks !

**Comment by MarkusTeufelberger** [comment]
Didn't test, but looks good and useful. I approve it, thanks a lot for the patch and the patience! :-)

**Comment by adragomir** [comment]
Pinging @philwo and thanks @MarkusTeufelberger. 
This is tested on a pretty large Bazel repository and works fine.

**Comment by philwo** [comment]
Merged! :D Thanks a lot, @adragomir!

**Comment by Globegitter** [comment]
@adragomir @MarkusTeufelberger this is breaking the `update_deb_packages` command for me with the following error:

```
(15:17:46) ERROR: /home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/rules_pkg/tools/update_deb_packages/src/BUILD:3:1: GoCompile external/rules_pkg/tools/update_deb_packages/src/linux_amd64_stripped/go_default_library%/github.com/bazelbuild/rules_pkg/tools/update_deb_packages/src.a failed (Exit 1): compile failed: error executing command 
  (cd /home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/execroot/__main__ && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=linux \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin \
  bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/linux_amd64_stripped/compile -sdk external/go_sdk -src external/rules_pkg/tools/update_deb_packages/src/update_deb_packages.go -dep github.com/knqyf263/go-deb-version -dep github.com/stapelberg/godebiancontrol -dep golang.org/x/crypto/openpgp -importmap 'github.com/knqyf263/go-deb-version=github.com/knqyf263/go-deb-version' -importmap 'github.com/stapelberg/godebiancontrol=github.com/stapelberg/godebiancontrol' -importmap 'golang.org/x/crypto/openpgp=golang.org/x/crypto/openpgp' -o bazel-out/host/bin/external/rules_pkg/tools/update_deb_packages/src/linux_amd64_stripped/go_default_library%/github.com/bazelbuild/rules_pkg/tools/update_deb_packages/src.a -package_list bazel-out/host/bin/external/go_sdk/packages.txt -- -I bazel-out/host/bin/external/com_github_knqyf263_go_deb_version/linux_amd64_stripped/go_default_library%/ -I bazel-out/host/bin/external/com_github_stapelberg_godebiancontrol/linux_amd64_stripped/go_default_library%/ -I bazel-out/host/bin/external/org_golang_x_crypto/openpgp/linux_amd64_stripped/go_default_library%/ -trimpath . -I . -p github.com/bazelbuild/rules_pkg/tools/update_deb_packages/src)

Use --sandbox_debug to see verbose messages from the sandbox
/home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/sandbox/linux-sandbox/1/execroot/__main__/external/rules_pkg/tools/update_deb_packages/src/update_deb_packages.go:479:64: undefined: components
GoCompile: error running subcommand: exit status 2
Target //:update_deb_packages failed to build
```

Will move to the previous commit in the meantime.

**Comment by adragomir** [comment]
@Globegitter can you do the `--sandbox_debug` thing ? Maybe we can get some better errors, or try and see what the issue is ?

**Comment by MarkusTeufelberger** [comment]
https://github.com/bazelbuild/rules_pkg/blob/master/tools/update_deb_packages/src/update_deb_packages.go#L479 really seems to reference `components` which haven't been defined anywhere in that function before.

**Pull request merged**
