### PR TITLE
Align pkg_rpm returned files with other rules

### PR DESCRIPTION
**Pull request by k0walik**
`pkg_rpm` returns both package file and a symbolic link, while other rules return only the actual file.

This is a follow up PR on the [comment](https://github.com/bazelbuild/rules_pkg/issues/685#issuecomment-1486158035) in #685.

### CODE REVIEW

**Comment by aiuto** [comment]
Leaving this one for @nacl.  They are the RPM expert and heavy user.

**Review by aiuto — APPROVED** [review]
Sorry for the lack of response here.
This seems fine. Now that I read it carefully, I see that very little is actually changing. The PR description had me looking for more.

**Comment by aiuto** [comment]
Still trying to get a handle on the CI failures. It doesn't make sense.

**Comment by aiuto** [comment]
Friendly ping. Can you try to update your branch and push again so we can see if CI is cleared up?

**Comment by k0walik** [comment]
Done! The CI is passing.

**Comment by aiuto** [comment]
Does this fix #685?

**Comment by k0walik** [comment]
Yes, we can close that one

**Comment by aiuto** [comment]
Thanks!

**Pull request merged**
