### PR TITLE
Stop running integration tests on ubuntu16. The platform is EOL and unsupported.

### PR DESCRIPTION
**Pull request by aiuto**
Remove ubuntu16 from CI.

### CODE REVIEW

**Comment by aiuto** [comment]
CI is very messed up. I am investigating with the Bazel team.

**Comment by nacl** [comment]
Do you still need a review on this?

**Comment by aiuto** [comment]
Sure. I am trying to be a good boy and not submit code unilaterally.
What I really wanted to do is make sure that Ubuntu 16 is not an important test platform for you.
If it is, we can leave it, but the rest of Bazel will soon leave it behind.

**Review by dannysullivan — APPROVED** [review]

**Comment by nacl** [comment]
> Sure. I am trying to be a good boy and not submit code unilaterally.
> What I really wanted to do is make sure that Ubuntu 16 is not an important test platform for you.
> If it is, we can leave it, but the rest of Bazel will soon leave it behind.

Ah, OK.  Wasn't sure if this was at all associate w/ that CI problem you were mentioning.  I'll take a look.

**Review by nacl — APPROVED** [review]
LGTM

**Pull request merged**
