### PR TITLE
Start removing licenses(notice) and replacing with license()

### PR DESCRIPTION
**Pull request by aiuto**
`licenses()` does not do anything.

### CODE REVIEW

**Comment by aiuto** [comment]
@teeler - can we do this?

**Comment by aiuto** [comment]
Lowered in urgency. It's going to make my imports harder if I do this today.

**Comment by aiuto** [comment]
friendly ping from reviewers.
license() is a no-op in Bazel. It is not used in Blaze when applicable_licenses is used.

**Review by Wyverald — APPROVED** [review]

**Review by cgrindel — APPROVED** [review]

**Comment by aiuto** [comment]
The failing test is unrelated to this. It is that --noenable_bzlmod does not work with bazel at head, and bazelci is ignoreing the explicit bazel version.

**Pull request merged**
