### PR TITLE
rpm: Refine prefix matching for sub RPMs to reduce fragility

### PR DESCRIPTION
**Pull request by kellyma2**
The current prefix matching for sub RPMs can potentially fail in two ways:

- if we have two overlapping prefixes we may match the shorter prefix against the wrong RPM
- the shorter prefix will match repeatedly even after finding its target

This change keeps track of which sub RPMs have already match so avoid
double matching a shorter prefix.  Additionally, we sort the sub RPM
list by name length in reverse order.  This ensures that we prefer to
match the longest prefixes first and avoid double matching with the
same prefix.

fixes: https://github.com/bazelbuild/rules_pkg/issues/875

### CODE REVIEW

**Comment by kellyma2** [comment]
This fixes https://github.com/bazelbuild/rules_pkg/issues/875

**Comment by cgrindel** [comment]
Can we add a test that verifies the behavior being fixed is fixed?

**Review by aiuto — COMMENTED** [review]
Looks good, but it could use a test.

**Comment by kellyma2** [comment]
> Can we add a test that verifies the behavior being fixed is fixed?

Yes.  I'll try to get back to that this week.

**Comment by kellyma2** [comment]
> Looks good, but it could use a test.

Done

**Review by cgrindel — APPROVED** [review]

**Review by aiuto — APPROVED** [review]
Thanks

**Pull request merged**
