### PR TITLE
Add %posttrans scriptlet to RPM package

### PR DESCRIPTION
**Pull request by k0walik**
RPM package specification defines `%posttrans` scriptlet, which can be particularly useful when upgrading a package. We should add it to the `pkg_rpm` build rule.

Reference: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#ordering

### CODE REVIEW

**Comment by cgrindel** [comment]
@k0walik #797 just merged disabling the doc builds. I believe that those are causing all/most of the failures in your CI. Could you update your branch with the latest?

**Review by cgrindel — COMMENTED** [review]
Overall, LGTM. A couple of comments:
- I did not notice a test leveraging `postrans_scriptlet_file`. Could you add one?
- Could you update your branch with the latest to address the doc_build failures?

**Comment by k0walik** [comment]
> * I did not notice a test leveraging `postrans_scriptlet_file`. Could you add one?

Sure! I modified `test/rpm/BUILD` to test both `xxx_scriptlet` and `xxx_scriptlet_file` attributes - it looks like file variant was not tested at all.

> * Could you update your branch with the latest to address the doc_build failures?

Done

**Review by cgrindel — APPROVED** [review]
LGTM. I won't merge it yet, so that @aiuto can take a look.

**Review by aiuto — APPROVED** [review]
This looks like it should work.
Thanks for improving the testing

**Pull request merged**
