### PR TITLE
Implement symlink and tree install for pkg_install

### PR DESCRIPTION
**Pull request by kgreenek**
Implement `_install_treeartifact` and `_install_symlink` functions or the pkg_install rule.

### CODE REVIEW

**Review by cgrindel — COMMENTED** [review]
Can you add some tests exercising this functionality?

**Comment by jacky8hyf** [comment]
Apologies, I have made a similar contribution for TreeArtifact in https://github.com/bazelbuild/rules_pkg/pull/885 , which causes a merge conflict for this pull request. I would still like to see symlinks working, though!

**Comment by aiuto** [comment]
I am closing this as a duplicate of #885

**Comment by kgreenek** [comment]
This is partially a duplicate, but my PR also added support for symlinks, in addition to the TreeArtifact implementation.

I'll rework mine when I have time and send a new PR with just that functionality.

**Pull request closed without merging**
