### PR TITLE
Provide more examples for pkg_rpm()

### PR DESCRIPTION
**Pull request by kellyma2**
This PR does three things:

* moves the existing rpm example into a subdirectory to make the examples easier to collect
* adds examples using the system rpmbuild (bzlmod and non-bzlmod)
* adds an example that uses pure `pkg_rpm()` with no specfile

### CODE REVIEW

**Review by cgrindel — APPROVED** [review]
This looks good to me. I noticed that CI is failing on Windows. @aiuto is that a flaky test?

**Comment by tonyaiuto** [comment]
i wlll look when i get back from vacation

**Comment by kellyma2** [comment]
> This looks good to me. I noticed that CI is failing on Windows. @aiuto is that a flaky test?

Looks like the failure was in pulling the repo, which I assume to be unrelated to my changes.

**Comment by aiuto** [comment]
Thanks.

**Pull request merged**
