### PR TITLE
Support duplicate file paths in tar archives

### PR DESCRIPTION
**Pull request by eejayes**
Duplicate path entries are made possible within tar archives, as per feature request described in #849.

RELNOTES: Duplicate path entry support within tar archives

### CODE REVIEW

**Comment by eejayes** [comment]
I will await design feedback before updating tests.

**Comment by aiuto** [comment]
I think the discussion in #849 came up with a good proposal. Whenever you're ready.

**Comment by eejayes** [comment]
Hello. Yes, I would agree. I have started to work on it.

**Comment by eejayes** [comment]
This provides `pkg_tar` with support for duplicate file paths. Tests added show that:
- an externally defined archive that is propagated through `pkg_tar` simply has it's structure preserved
- adding a path via `srcs` which conflicts with a path within an archive in `deps` properly results in duplicates
- adding two archives via `deps` which have conflicting paths properly results in duplicates

In the pre-existing code, `deps` are added after `srcs`. Thus for paths appearing both in `deps` and `srcs`, it is the one in `deps` which will appear later in the archive list and will thus prevail when an archive is unpacked. This conflicts with common command line _tar_ tools where:
1. users may specify which archive is subject to modification during an archive concatenation operation
2. the archive is implicitly the modification subject in an operation combining a file and archive

It would be straight-forward to adapt the code to the second case. The first case would however require a mechanism to specify which archive (i.e. `dep`) is the modification subject, i.e. the sequence in which archives should be extended. The proposed iteration does not solve these. Instead it requires that multiple sequential `pkg_tar` operations be declared when there are path conflicts between any pair of `deps` or `srcs`.

The purpose of duplicate support is to support evolution of artifacts as consistent with typical _tar_ utility behavior. Since files can only serve to specify change, they are never artifacts and thus `srcs` conflicts which could exist within the scope of a single `pkg_tar` artifact should be solved prior to it's declaration. Adding duplicates to `srcs` should be an error. 

Outside of the discussion in the issue #849, there were some unforeseen interactions with `create_parents`. Currently because duplicates are not allowed, if `create_parents` is specified for a pre-existing directory, it will not be created. However with the support of `allow_duplicates_from_deps`, an additional directory could be created with the arbitrary default permissions. Since directory permissions of a pre-existing path represent information that is either equally good to the default permissions which are applied in the absence of information, or better in the case that a user has explicitly declared them, it makes more sense to use the pre-existing path info even with `allow_duplicates_from_deps`.

Future improvement considerations are:
1. Reversal of file and tar addition ordering to address (2) above
2. Sequencing mechanism for tar construction (1) above
3. Adding duplicates file paths to `srcs` should be an error.

**Comment by aiuto** [comment]
I can look at this later today.

**Review by aiuto — APPROVED** [review]
Sorry for the slowness. Things got busy here.

**Pull request merged**
