### PR TITLE
Fix RPM tests after #242

### PR DESCRIPTION
**Pull request by nacl**
#242 changed up the location of the RPM building tests.  Unfortunately, I found
local errors with all of the rpmbuild tests, mostly related to additional files
that need to be moved.

Tested locally with `bazel test //...`.

### CODE REVIEW

**Review by aiuto — APPROVED** [review]
Whoops. My bad.  I did the change on a mac, so I was skipping the tests.
And, of course, the tests don't run in CI., so it is hard to see.

We really need to figure out how to build rpmbuild for the linux test runs.

**Comment by nacl** [comment]
> Whoops. My bad. I did the change on a mac, so I was skipping the tests.
> And, of course, the tests don't run in CI., so it is hard to see.
> 
> We really need to figure out how to build rpmbuild for the linux test runs.

Or ensure that ends up in the CI images: https://github.com/bazelbuild/continuous-integration/issues/1039.  It would seem to be the easy way out, at least for ensuring that the common use cases for RPM packaging (Linux builds on Linux) work.

**Comment by aiuto** [comment]
Are you able to merge this? Or must I?

**Comment by nacl** [comment]
> Are you able to merge this? Or must I?

Just did. Was taking care of some other stuff.

**Pull request merged**
