### PR TITLE
docs: add a note in pkg_tar#strip_prefix docs (v.0.8.0) about flattening

### PR DESCRIPTION
**Pull request by jhchabran**
Hey folks, here is a very inconsequential PR which could save some time to new users. 

From the perspective of someone who just started using `rules_pkg`, I was really confused to learn that if I don't want to flatten the files structure I have to use the undocumented `strip_prefix = "."` magic trick. 

While there is an ongoing discussion over https://github.com/bazelbuild/rules_pkg/issues/354 on this precise issue, I feel that it would save a lot a time for new users stumbling across this problem by having a quick note in the existing docs, while the conversation continues over there.

### CODE REVIEW

**Comment by aiuto** [comment]
It would be more useful to correct the text in the code and regenerate the docs.
Of course, it's hard to regenerate 0.8.0 docs, so this change is still needed too.

**Comment by jhchabran** [comment]
@aiuto updated :)

**Review by aiuto — APPROVED** [review]
I have no idea why the tests are failling

**Comment by aiuto** [comment]
Going to try to merge and then I will fix tests after.

**Pull request merged**
