### PR TITLE
Merge changes for #221 into "main"

### PR DESCRIPTION
**Pull request by nacl**
Includes the fixes from #221 into the new "main" branch.  It was previously committed to the "master" branch.

### CODE REVIEW

**Comment by aiuto** [comment]
We may need @davschne to resend the PR to the main branch.  Or just redo the change without attribution.

**Comment by davschne** [comment]
I'll redo my PR. Sorry about that; I assumed master was the default branch. For my future understanding, what's the role of master in this repository?

**Comment by aiuto** [comment]
On Tue, Sep 8, 2020 at 5:00 PM David Schneider <notifications@github.com>
wrote:

> I'll redo my PR. Sorry about that; I assumed master was the default branch.
>
Not your fault. The change was easy to miss unless you read every issue and
PR.

> For my future understanding, what's the role of master in this repository?
>
I renamed master to main about a month ago.
https://github.com/bazelbuild/rules_pkg/issues/199

Everyone should rename their master branches to main if they have work in
progress.
In the future, I will try harder to check that PRs are not against master.

**Comment by davschne** [comment]
Thanks for the clarification, @aiuto.

Here's a new PR targeting `main`: https://github.com/bazelbuild/rules_pkg/pull/230

I rebased onto current HEAD of `main`, so it's a new commit with the same content.

**Comment by nacl** [comment]
Obviated by #230.  Thanks!

**Pull request closed without merging**
