### PR TITLE
manifest: Allow for TreeArtifacts in PackageFilesInfo

### PR DESCRIPTION
**Pull request by nacl**
The package-independent JSON manifests currently do not consider whether a
"file" in a `PackageFilesInfo` provider is actually a file or a directory.  This
change provides this awareness.

This also fixes up some other (apparent) logic issues related to directories,
and additionally provides a test.  Since the tests now involve generated
TreeArtifacts, this change also forces the manifest generation tests to use the
manifest "short_path".

There may be a better way to do this, but it seems to work for now.

### CODE REVIEW

**Comment by aiuto** [comment]
Sorry for the delay. Is it ready for review, or is the failing mac test a problem?

**Comment by nacl** [comment]
> Sorry for the delay. Is it ready for review, or is the failing mac test a problem?

No worries.  It's a Windows test, and I need to actually set up an environment with which to diagnose the problem.  The code seems to work fine otherwise.

I'll let you know when the code is ready for review.

**Comment by beasleyr-vmw** [comment]
Seems like a touchup in `build_tar.py` is necessary. (If the Starlark portion already forces use of `/` as a delimiter in the manifest file, then we probably don't need to adapt `tree_top`. The important conversions are to `root` as returned by `os.walk` and the retval from `os.path.join`.)

```diff
--- a/pkg/private/build_tar.py
+++ b/pkg/private/build_tar.py
@@ -223,10 +223,14 @@ class TarFile(object):
        names: (username, groupname) for the file to set ownership. `f` will be
          copied to `self.directory/destfile` in the layer.
     """
+    # We expect /-style paths.
+    tree_top = os.path.normpath(tree_top).replace(os.path.sep, '/')
+
     dest = destpath.strip('/')  # redundant, dests should never have / here
     if self.directory and self.directory != '/':
       dest = self.directory.lstrip('/') + '/' + dest

+    # Again, we expect /-style paths.
     dest = os.path.normpath(dest).replace(os.path.sep, '/')
     if ids is None:
       ids = (0, 0)
@@ -235,6 +239,10 @@ class TarFile(object):

     to_write = {}
     for root, dirs, files in os.walk(tree_top):
+      # While `tree_top` uses '/' as a path separator, results returned by
+      # `os.walk` and `os.path.join` on Windows may not.
+      root = os.path.normpath(root).replace(os.path.sep, '/')
+
       dirs = sorted(dirs)
       rel_path_from_top = root[len(tree_top):].lstrip('/')
       if rel_path_from_top:
@@ -244,7 +252,7 @@ class TarFile(object):
       for dir in dirs:
         to_write[dest_dir + dir] = None
       for file in sorted(files):
-        to_write[dest_dir + file] = os.path.join(root, file)
+        to_write[dest_dir + file] = os.path.join(root, file).replace(os.path.sep, '/')

     for path in sorted(to_write.keys()):
       content_path = to_write[path]
```

**Review by beasleyr-vmw — COMMENTED** [review]
w/r/t the Windows test failure, seems like a touchup in `build_tar.py` is necessary. See example patch below. (If the Starlark portion already forces use of `/` as a delimiter in the manifest file, then we probably don't need to adapt `tree_top`. The important conversions are to `root` as returned by `os.walk` and the result from `os.path.join`.)

```diff
--- a/pkg/private/build_tar.py
+++ b/pkg/private/build_tar.py
@@ -223,10 +223,14 @@ class TarFile(object):
        names: (username, groupname) for the file to set ownership. `f` will be
          copied to `self.directory/destfile` in the layer.
     """
+    # We expect /-style paths.
+    tree_top = os.path.normpath(tree_top).replace(os.path.sep, '/')
+
     dest = destpath.strip('/')  # redundant, dests should never have / here
     if self.directory and self.directory != '/':
       dest = self.directory.lstrip('/') + '/' + dest

+    # Again, we expect /-style paths.
     dest = os.path.normpath(dest).replace(os.path.sep, '/')
     if ids is None:
       ids = (0, 0)
@@ -235,6 +239,10 @@ class TarFile(object):

     to_write = {}
     for root, dirs, files in os.walk(tree_top):
+      # While `tree_top` uses '/' as a path separator, results returned by
+      # `os.walk` and `os.path.join` on Windows may not.
+      root = os.path.normpath(root).replace(os.path.sep, '/')
+
       dirs = sorted(dirs)
       rel_path_from_top = root[len(tree_top):].lstrip('/')
       if rel_path_from_top:
@@ -244,7 +252,7 @@ class TarFile(object):
       for dir in dirs:
         to_write[dest_dir + dir] = None
       for file in sorted(files):
-        to_write[dest_dir + file] = os.path.join(root, file)
+        to_write[dest_dir + file] = os.path.join(root, file).replace(os.path.sep, '/')

     for path in sorted(to_write.keys()):
       content_path = to_write[path]
```

**Pull request merged**
